spring:
  datasource:
    dynamic:
      datasource:
        master: # 主数据库
          url: jdbc:mysql://localhost:3306/edu_trip?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: c484bb0c911cfa33
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379 # 端口
    database: 4 # redis第4个库
    host: 127.0.0.1 # 地址
#    password: Systek@!redis # 密码

# swagger开关
swagger:
  enable: false
# 定时任务开关
scheduled:
  enable: true
# 订单流水前缀
code:
  prefix: 11TW

edu:
  file:
    upload-path: /www/file # 线上linux环境文件存储目录
    domain: https://cjcbygc.systekcn.com/yanxue_api # 线上资源访问域名
unionPay:
  notifyUrl: https://cjcbygc.systekcn.com/yanxue_api/trip/order/unionPayNotify # 银联回调
